function write_loc_file(mridir, filename, subject)

    load(fullfile(mridir, subject, [subject , '_elec_mni_frv_new.mat'])); 
    load(fullfile(mridir, subject, [subject , '_elec_acpc_f_new.mat'])); 

    loc = table(elec_mni_frv.label, ...
                elec_acpc_f.chanpos, ...
                elec_mni_frv.chanpos, ...
                [elec_mni_frv.loc{:, 2}]', ... 
                'VariableNames', {['p' subject], 'acpc', 'mni', 'loc'}); 

    writetable(loc, filename, ...
               'Sheet', ['p' subject]); 
end
