function [fig] = plot_bar_in_out_strength(patientStructFull, bad_channels, prctile_thr, cmap)
% PLOT_BAR_IN_OUT_STRENGTH plots bar graphs of in-strength, out-strength, and spike rate.
%
% Syntax:
%   fig = plot_bar_in_out_strength(patient, patientStructFull, paths, bad_channels, prctile_thr, cmap)
%
% Input:
%   - patientStructFull: A structure with subfields:
%   - patientStructFull.epochsList: Subfield containing the following fields:
%           - Fs (double): Sampling frequency.
%           - X_raw (matrix): Matrix of the signal.
%           - chan_names (cell array): Names of the channels.
%   - bad_channels: Channels to mark as bad.
%   - prctile_thr: Percentile threshold for highlighting good channels.
%   - cmap: Colormap for the plot (optional).
%
% Output:
%   - fig: The generated figure.

    if nargin < 4
        bar_color = 'b'; 
        thr_color = 'r'; 
    else
        bar_color = cmap(1, :); 
        thr_color = cmap(2, :); 
    end
    
    chan_names = patientStructFull.epochsList.chan_names;
    
    [in, out] = get_in_out_str(patientStructFull); 
    spike_rate = get_patientStructFull_spike_rates(patientStructFull); 
    if size(spike_rate, 1) > size(spike_rate, 2)
        spike_rate = spike_rate';
    end 
    
    fig = figure('units', 'normalized', 'outerposition', [0 0 1 1]); 

    subplot(4, 1, 1)
    build_rate_bar(out, ...
                   'xticklabels', chan_names, ...
                   'color', bar_color, ...
                   'titlestr', 'Outstrength', ...
                   'bad_channels', bad_channels, ...
                   'good_channels', find(out > prctile(out, prctile_thr)), ...
                   'fontsize', 10); 
    hold on;  
    line(xlim, [prctile(out, prctile_thr), prctile(out, prctile_thr)], ...
         'color', thr_color, 'LineWidth', 1);

    subplot(4, 1, 2)
    build_rate_bar(out .* spike_rate, ...
                   'xticklabels', chan_names, ...
                   'color', bar_color, ...
                   'titlestr', 'Outstrength .* Spike rate', ...
                   'bad_channels', bad_channels, ...
                   'good_channels', find(out .* spike_rate > prctile(out .* spike_rate, prctile_thr)), ...
                   'fontsize', 10); 
    hold on;  
    line(xlim, [prctile(out .* spike_rate, prctile_thr), prctile(out .* spike_rate, prctile_thr)], ...
         'color', thr_color, 'LineWidth', 1);

    subplot(4, 1, 3)
    build_rate_bar(in, ...
              'xticklabels', chan_names, ...
              'color', bar_color, ...
              'titlestr', 'Instrength', ...
              'bad_channels', bad_channels, ...
              'good_channels', find(in > prctile(in, prctile_thr)), ...
              'fontsize', 10); 
    hold on;  
    line(xlim, [prctile(in, prctile_thr), prctile(in, prctile_thr)], ...
         'color', thr_color, 'LineWidth', 1);

    subplot(4, 1, 4)
    build_rate_bar(spike_rate, ...
              'xticklabels', chan_names, ...
              'color', bar_color, ...
              'titlestr', 'Spike rate', ...
              'bad_channels', bad_channels, ...
              'good_channels', find(spike_rate > prctile(spike_rate, prctile_thr)), ...
              'fontsize', 10); 
    hold on;  
    line(xlim, [prctile(spike_rate, prctile_thr), prctile(spike_rate, prctile_thr)], ...
         'color', thr_color, 'LineWidth', 1);
     
end




 